modules = {
    federationRasterSearch{
        resource url: [plugin: "omar-core", dir: "js/prototype", file: "prototype.js"]
        resource url: [plugin: 'omar-common-ui', dir: 'js', file:'OMAR.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file:'hashmap.js']
        resource url: [plugin: 'omar-core', dir: 'js', file: 'coord.js']
        resource url: [plugin: 'omar-core', dir: 'js', file: 'jquery.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery', file: 'jquery-ui.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery', file: 'jquery.layout-latest.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery/DataTables-1.9.4', file: 'jquery.dataTables.min.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery/DataTables-1.9.4', file: 'jquery.datatables-ext.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery/DataTables-1.9.4', file: 'jquery.pagination.js']
      resource url: [plugin: 'omar-common-ui', dir: 'css', file: 'jquery.contextmenu.css']
      resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'jquery.contextmenu.js']
        resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery', file: 'jquery.dataTables.css']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'json2.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/underscore', file:'underscore-1.4.2.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'backbone-min.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'SelectedCollection.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'DisplayUnitModelView.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'EllipsoidModel.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'BboxModelView.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'PointModelView.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'UnitsModelView.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'CqlModelView.js']
       resource url: [plugin: 'omar-ogc', dir: 'js', file: 'WfsModel.js']
       resource url: [plugin: 'openlayers', dir: 'css', file: 'mapwidget2.css']
       resource url: [plugin: 'openlayers', dir: 'js/theme/default', file: 'style.css']
       resource url: [plugin: 'openlayers', dir: 'js', file: 'OpenLayers.js']
       resource url: [dir: 'js', file: 'spin-min.js', plugin: 'omar-core']
       // css resources for jquery
       resource url: [plugin: 'omar-common-ui', dir: 'css', file: 'jMenu.jquery.css']
       resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery', file: 'layout-default-latest.css']
       resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery/smoothness', file: 'jquery-ui-1.9.2.custom.css']
       resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery', file: 'jquery-ui-timepicker-addon.css']

       resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery', file: 'jquery-ui-timepicker-addon.js']

       resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'jMenu.jquery.js']
       resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'DateModelView.js']

       resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'SearchMenuModelView.js']

       resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'MapModelView.js']
       resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'ViewSelector.js']

       resource url: [dir: 'js', file: 'ServerListModelView.js']
       resource url: [dir: 'js', file: 'WfsDataModelView.js']

       resource url: [dir: 'css', file: 'search.css']
       resource url: [dir: 'js', file: 'search.js']
       resource url: [dir: 'js', file: 'condition-builder.js']
    }
    federationAdmin{
        resource url: [plugin: "omar-core", dir: "js/prototype", file: "prototype.js"]
        resource url: [plugin: 'omar-common-ui', dir: 'js', file:'OMAR.js']
        resource url: [plugin: 'omar-core', dir: 'js', file: 'jquery.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery', file: 'jquery-ui.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/jQuery', file: 'jquery.layout-latest.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'json2.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js/underscore', file:'underscore-1.4.2.js']
        resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'backbone-min.js']
        resource url: [plugin: 'omar-common-ui', dir: 'css', file: 'jMenu.jquery.css']
        resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery', file: 'layout-default-latest.css']
        resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery', file: 'layout-default-latest.css']
        resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery/smoothness', file: 'jquery-ui-1.9.2.custom.css']
        resource url: [plugin: 'omar-common-ui', dir: 'css/jQuery', file: 'jquery-ui-timepicker-addon.css']
      resource url: [plugin: 'omar-common-ui', dir: 'js', file: 'jMenu.jquery.js']
        resource url: [dir: 'js', file: 'spin-min.js', plugin: 'omar-core']
        resource url: [dir: 'css', file: 'admin.css']
        resource url: [dir: 'js', file: 'admin.js']
    }
}